- package-lock.json
- package.json
- src/App.jsx
- src/components/SwitchTab.jsx
- src/pages/AutoCounterPage.jsx
- src/pages/TimerPage.css
- src/pages/TimerPage.jsx
Overview:
This PR introduces significant improvements to the TimerPage component, enhancing the user interface and experience by implementing responsive design and refined button styles.
Changes Made:
Button Layout and Styling:
Introduced a new .button-container class to organize the Start, Pause, and Reset buttons using Flexbox. This ensures equal spacing and alignment for better usability.
Customized individual button styles for the Start, Pause, and Reset buttons, providing distinct colors and hover effects to enhance visual feedback.
Responsive Design:
Adjusted padding and margins to ensure a consistent layout across different screen sizes, improving accessibility and user experience.
Theme Support:
Maintained existing theme support (light and dark modes) throughout the TimerPage …
> feat : Added Timer Page 

- src/components/LapAnalysis.jsx
- src/components/LapVisualization.jsx
- src/components/laplist.jsx
- src/components/timer.jsx
- src/pages/AutoCounterPage.jsx
This pull request introduces enhanced lap time analysis and visualization features to the existing stopwatch functionality. The improvements aim to provide users with deeper insights into their performance during timed activities.
- **Average Lap Time:** Calculates and displays the average time taken for all laps.
- **Fastest Lap:** Identifies and displays the lap with the fastest time.
- **Slowest Lap:** Identifies and displays the lap with the slowest time.
- **Bar Chart:** Implements a bar chart to visually display each lap's time.
A video demonstration showcasing the new features has been included for reference. 
https://github.com/user-attachments/assets/b5435313-837c-46d6-a34a-8628d7187667
> Enhance Stopwatch with Lap Time Analysis and Visualization Features

- package-lock.json
- package.json
- src/App.jsx
- src/components/Footer.jsx
- src/components/navbar.jsx
- src/pages/WorldClockPage.jsx
I have made toggle theme icon globally functional so that it work in all route.
problem no.-#21
> Toggle theme icon functionality improved

- Contributing.md
- README.md
Fixed #31 
This pull request introduces a `CONTRIBUTING.md` file to the repository to provide clear guidelines for contributors. The document outlines the steps to fork the repository, create a new branch, commit changes, and submit a pull request. By establishing these guidelines, we aim to facilitate smoother collaboration and encourage more contributions from the community.
- Added `CONTRIBUTING.md` file with detailed contribution steps.
- Included instructions for forking, branching, committing, and submitting PRs.
This enhancement will help ensure that all contributors understand the contribution process and maintain a consistent workflow throughout the project.
> Fixed #31 : Create Contributing.md to Facilitate Community Contributions

- README.md
Added Contributors profile in the README.md file as a token of gratitude to them ❤️ .
> Added Contributors profile

- package-lock.json
- src/components/Footer.jsx
Hey @param-code , 
closes issue number #44 
done with the X logo at the footer
nothing else in the code has changed. If you feel anything remaining or you have some extra issues I'd love to work on it.
Thank you for this opportunity.
> changed the twitter logo to X logo

- src/components/controls.jsx
@param-code 
The Issue of Button UI Enhancement is Done.
I added some micro-interactions in the button .
You can see it here👇.
https://github.com/user-attachments/assets/1532b8aa-0878-44a3-9916-5c6b8745c20d
Now You can merge it.
> Need Enhancement of Button UI Problem Solved

- src/components/navbar.jsx
corrected the github navigation...................
> Corrected the navigation thing

- Code of Conduct.md
#issue 27 solved 
code of conduct file added
> Code of conduct file added

- src/components/navbar.jsx
> added proper github repo link to the button in navbar

- Dockerfile
multistage Dockerfile added
docker container running
also tested
docker build 
`docker build -t counter . `
docker run
`docker run -p 8080:80 counter `
> Feature(Docker) : add production-ready Dockerfile #67

- .github/ISSUE_TEMPLATE/bug_report_template.md
- .github/ISSUE_TEMPLATE/custom_issue_template.md
- .github/ISSUE_TEMPLATE/feature_request_template.md
hey @param-code,
i have added the issue template to this pr. can you review it and merge it?
please dont forget to add labels to this pr.
> Added issue templates for custom issues, bugs, and feature requests. Fixes #48

- src/pages/SignUpPage.jsx
Hi, @param-code i have done #100 please check.
<br/>
> added signIn toggle functionality

- src/pages/TimerPage.jsx
fixes issue #101 
input text visible for darkmode as well as light mode.
fixed the btn design of start, reset and pause
> fixed for darkmode

- package-lock.json
- package.json
- src/components/Footer.jsx
- src/components/GoogleTranslate.jsx
-added a interface to select a language you want to view website in the footer
-the website will be changed to selected language
https://github.com/user-attachments/assets/1f4b6602-2ada-468f-abef-fb387eafe46c
> google multilanguage integrated

- package-lock.json
- package.json
- src/components/controls.jsx
- src/components/timer.jsx
- src/pages/Counter.jsx
- tailwind.config.js
progress bar done under the buttons and timer #99
> added progress bar

- src/pages/SignUpPage.jsx
Fixes #110  Adding placeholder to signup page so the user get some hint what to enter in input tag.
Now Behaviour:
@param-code Please review it and merge accordingly:)
> BUG: Adding placeholder in SignupPage

- src/pages/SignUpPage.jsx
Fixes #112  When we click on input tag of login and signup form it show me double border but now when we click on same input tag now it will show a single blue border.
@param-code Please review it and merge accordingly!
> BUG: Remove Double border

- package.json
- src/main.jsx
- src/pages/SignUpPage.jsx
Fixes #114 When user try to login and signup and it click on the login button or signup button then it navigates to home page and also get notified by website login successfully and signup successfully.
https://github.com/user-attachments/assets/68700f41-c060-412a-b6cc-bb349872e6dc
Please download react-hot-toast package dependency, using npm i react-hot-toast
@param-code Please review it and merge accordingly!
> Feat: Toast feature added for notification

- README.md
Pull Request: Updated README for navigable table of contents
Overview
This pull request updates the README file to improve navigation through the table of contents. The changes ensure that the sections can be easily accessed by clicking on the corresponding links.
Changes Made
- Updated the formatting of section headers to ensure compatibility with Markdown navigation.
- Ensured that all links in the table of contents correctly point to their respective sections.
- Maintained the use of emojis for a visually appealing layout while ensuring navigability.
Benefits
- Users can easily navigate the README file, enhancing the overall user experience.
- The organization of the document is improved, making it easier to find relevant sections quickly.
> Updated README for navigable table of contents

- readme1.md
#77 Since CODE OF CONDUCT is done by someone else so I've updated the README.md file with the following:
1)IMPORTANT GUIDELINES while CONTRIBUTING
2)COMMUNITY GUIDELINES while CONTRIBUTING
3)CODE REVIEWS.
I've updated the README.md file so that valuable and genuine contributions are made to this project to make it successful
> README.md file updated with "IMPORTANT GUIDELINES","COMMUTNITY GUIDELINES" and "CODE REVIEWS"

- package-lock.json
- package.json
- src/App.jsx
- src/components/Footer.jsx
- src/pages/Contributors.css
- src/pages/Contributors.jsx
Issue : #127
I have added the contributors page to the website.
It matches the overall theme of website.
It is linked to the footer so that navigation will be easy from home page.
https://github.com/user-attachments/assets/302449fc-face-4fd1-9ac7-e244d6b4c87f
> Added Contributor's Page

- package-lock.json
- src/pages/TimerPage.css
- src/pages/TimerPage.jsx
@param-code , I've done the following improvements:
1. Added user-friendly pop-up notifications using CSS animations for timer actions (start, pause, resume, reset).
2. Implemented input validation to ensure the timer cannot start with negative values.
here is the preview:
https://github.com/user-attachments/assets/a5fe9120-d437-43b2-8669-059979b13521
> rectified negative timer ,and added popups.

- index.html
- preloader.js
- preloaderStyle.css
Issue Fixed: #98 
Styling has been applied to the preloader and scroll bar. The preloader and Scroll bar is present on all pages of the website with styling. The scroll bar behaviour has been improved and the thumb and track have been redesigned, resulting in improved scroll behaviour.
*Improvements:*
1. *Optimized Preloader:* Enhanced the preloader animation on the landing, timer, and world clock pages to improve user experience.
2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.
3. *Dedicated Preloader Script and Styling:* Applied a separate JavaScript and CSS  Styling to manage the preloader functionality and scroll bar scrolling behaviour, ensuring better code organization and maintainability.
The program was tested locally on a …
> improve preloader and scroll bar

- package-lock.json
- src/pages/Contributors.css
- src/pages/Contributors.jsx
Fixes Issue #144
Added Navbar to the Contributor Page: Introduced a responsive navigation bar to improve the user experience and provide easy access to different sections of the site.
Implemented Dark Theme: Added a dark mode toggle option for the contributor page, allowing users to switch between light and dark themes seamlessly.
a) Missing Navbar in the Contributor Page: Previously, the contributor page lacked a navigation bar. I have added the Navbar component to ensure better navigation across the site.
b) Dark Theme Implementation: As per user demand, the dark theme has been integrated into the contributor page, giving it a modern touch and aligning it with the rest of the site’s dark mode feature. This makes the user experience smoother, especially in low-light environments. …
> Added Navbar and Dark theme in contributor page (Issue no #144)

- src/components/Footer.jsx
- src/components/laplist.jsx
- src/index.css
fixed by draging down the select langauge
aligined the text to center
> fixed issue : #159

- package-lock.json
- src/App.jsx
- src/components/About.jsx
- src/components/navbar.jsx
- src/components/ui/card.jsx
This pull request introduces the About Page, designed to offer users a visually appealing and informative overview of the app. The page highlights key functionalities.
Fixes: #151 
https://github.com/user-attachments/assets/c7a5a182-2bb0-4f0d-8149-522903a185cc
> Add about_page

- src/pages/Counter.jsx
- src/pages/SignUpPage.jsx
Fixes Issue #177 
Dark Mode Implementation: Integrated a dark mode toggle function into the navbar, allowing users to switch themes easily while using the timer app. Additionally, the toggle button for dark mode has been removed from the timer interface for a cleaner design.
Sign-Up Functionality Improvement: Resolved an issue with password visibility toggling on the sign-up page. Users can now easily view or hide their passwords while entering them, enhancing user experience and accessibility.
a) Dark Mode Toggle: Users can now toggle between light and dark themes from the navbar, enhancing the overall user experience and accessibility.
b) Password Visibility Toggle: Implemented a feature in the signup form that allows users to toggle password visibility, improving usability during …
> Dark mode in stopwatch page and sign up minor issue

- src/App.jsx
- src/pages/AutoCounterPage.jsx
- src/pages/WorkTracker.jsx
work tracker added : #79  done 
Add a functionality of we can set the time for particular work or subject and when its time get over there is a alert message prompt with it and showing the time is over. So By this your project use cases increase for someone to solve work with particular time interval type.
although i have added a button on the main page in center just for your project usecase increases by this functionality.
https://github.com/user-attachments/assets/fc434e36-9cf4-4fd4-8cdd-a1e046e5ef2a
> work tracker added : #79 done 

- src/components/Auth/Template.jsx
I've updated the authentication template component and am fixing the responsiveness bugs. Here is the result after making changes, kindly review it.
**After**:
https://github.com/user-attachments/assets/69373150-622e-4124-a626-182660d47a9a
**Before**:
> Auth page responsiveness issue fixed.

- backend/package-lock.json
- backend/package.json
- package-lock.json
- package.json
- src/components/Auth/LoginForm.jsx
- src/components/Auth/SignupForm.jsx
- src/validations/validation.js
I have added input validation to login and signup page
Pls check
> added validation

- package-lock.json
- src/pages/WorkTracker.jsx
Fixes Issue #194 
Dark Mode Implementation: Integrated a dark mode toggle function into the navbar, allowing users to switch themes easily while using the timer app.
a) Dark Mode Toggle: Users can now toggle between light and dark themes from the navbar, enhancing the overall user experience and accessibility.
The addition of the dark mode feature allows users to personalize their experience and improve readability in different lighting conditions. 
Enhancement (non-breaking change that improves the functionality and user experience)
My code follows the style guidelines of this project
I have performed a self-review of my code
I have commented my code, particularly in hard-to-understand areas
New and existing unit tests pass locally with my changes
Any dependent changes have been merged …
> Added dark theme in "WorkTracker page"

- package-lock.json
- package.json
- src/components/SpotifyPlayer.jsx
Issue Fixed.
Now when cursor approaches Spotify icon, then music player appears.
Closes #172
> [Bug]: Spotify Music Player Window hovers Appears Unexpectedly.

- backend/Dockerfile
Hello
I have added the dockerfile in the server
The env variables need to be passed while running the container or while building the image
> added dockerfile

- index.html
I have added the scroll to top button
https://github.com/user-attachments/assets/e649a140-1193-41b3-a968-9673a94ffff7
@param-code please review and allow merge and also assign the level 2, gssoc-extd, hacktoberfest labels
i hope ull consider it
> Added Scroll to top button

- src/components/navbar.jsx
This pull request introduces several enhancements to the `Navbar` component in the `src/components/navbar.jsx` file. The following modifications have been made:
1. **Responsive Button Layout**: The GitHub, Globe, Info, and Theme Toggle buttons are displayed in a single line for better accessibility and usability.
2. **Button Labels**: The GitHub and Globe buttons now include text labels ("Timer" and "World Clock") displayed beside their respective icons when the menu is toggled for small screens.
3. **CSS Separation**: All related styles have been separated into `navbar.css` for cleaner code and easier maintenance.
- Closes #219
_Please feel free to reach out if there are any questions regarding the changes made in this pull request._
> Updated Navbar component for improved responsiveness and functionality

- src/components/navbar.jsx
- src/pages/WorkTracker.jsx
Fixes #223 and #222 
- I have added a new icon for "contributors" page on navbar!
- Fixed Text issue in "WorkTracker" page too! 
**Thank you for assigning issues! (I know I spam a lot here xD)**
> Contributors page added to Navbar

- src/App.jsx
- src/pages/Error404.jsx
Issue - #251
Added Error404 page when user tries to connect to an undefined path.
> Added Error404 page 

- src/App.jsx
- src/components/Footer.jsx
- src/pages/PrivacyPolicy.css
- src/pages/PrivacyPolicy.jsx
Issue: https://github.com/param-code/counter-app/issues/231
Privacy and Policy page is added to the footer, when the user clicks on that link it will be redirected to a different webpage.
> New Privacy and Policy is added

- src/components/Footer.jsx
- src/components/css/Footer.css
I am implementing a 3D hover effect on the logo, as well as a hover animation effect on the footer heading. Additionally, I will implement an underline animation for the navigation items. #220 
https://github.com/user-attachments/assets/8315f2a1-29e6-4063-8ec2-dc0a93ac44e6
> Added 3d hover on logo improve the styling of footer heading and footer items

- package-lock.json
- src/App.jsx
- src/components/Auth/LoginForm.jsx
- src/components/Auth/PasswordRecovery.jsx
- src/services/operations/authAPI.js
Pull Request: Password Recovery Feature
Related Issue #233 
Description of Changes
This pull request introduces a Password Recovery feature to improve user experience by allowing users to securely reset their passwords when forgotten. The feature includes:
Backend logic for password recovery requests.
Frontend updates with a "Forgot Password?" option on the login screen.
Email verification for secure password resets.
Validation to prevent unauthorized password changes.
Screenshots / Demo
https://github.com/user-attachments/assets/cc2d75e4-7324-41fd-8579-5d5f4b71e12d
> Password-Recovery-Feature

- src/components/Auth/LoginForm.jsx
- src/components/Auth/SignupForm.jsx
updated the sign-up/login page with google/apple login with modern signup/login page..
**issue #246** 
now----
before---
> added  google /apple login & change the ui of signup/login page 

- src/App.css
- src/App.jsx
- src/components/Auth/LoginForm.jsx
- src/components/Auth/SignupForm.jsx
@param-code 
I have enhanced the default scroll bar
Kindly check it out
https://github.com/user-attachments/assets/45b12a4d-d98a-4da8-a167-82769163659d
> enhanced default scroll bar

- src/components/About.jsx
I have made all the proposed changes in the "**About Page**".
Changes are as follows :
1. **Hover effect** on 4 box cards on the right side in Initial part of about page.
2. Customizing and redesigning app info in '**About Counter Clock**' section.
3. Beautification of '**Our Features**' section.
4. User should get a notification once they have subscribed the newsletter in '**Get in Touch**' section.
5. Adding '**Testimonials**' section in About page where experience and review of users will appear in slidable cards format.
**After Changes :**
🔢 
🔢 
🔢 
🔢 
🔢
> Feature : About Page Improved

- src/components/Auth/LoginForm.jsx
- src/components/Auth/Review.jsx
- src/components/Auth/SignupForm.jsx
@param-code 
I have added close feature to the rating section
Kindly check it out
issue no : #269 
https://github.com/user-attachments/assets/725a4d8e-d12e-491b-9abf-d006bdd056c6
> added close feature to rating

- Contributing.md
I have enhanced the document and also added some new sections
Done the following changes :-
1) Enhanced the project structure
2) Added code of conduct section
2) Added star our repository section
3) Added need help with the basics section
4) Added first pull request steps section
5) Added additional method of contributing through GitHub desktop section
6) Added good coding practices section
7) Added pull request process
8) Add issue request section
9) Added thank you section
Fixes:[#274 ]
Closes:[#274 ]
> Done enhancements and also added some new sections

- backend/.env
- backend/controllers/othercontrollers.js
- backend/index.js
- backend/package-lock.json
- backend/package.json
- src/pages/Feedback.css
- src/pages/Feedback.jsx
Feedback backend frontend functionality working #278 done
https://github.com/user-attachments/assets/2998e024-8527-4753-ae36-fdf4368f41ca
So what i did changes -
1. Create an api for the sending mail to the project admin mail.
2. Nodemailer setup.
3. create route and test it.
4. making fetch request connect with it in frontend.
5. Making feedback form responsive.
6. All need steps you have to perform I have write in the .env file.
Output -
You need to take care of email id and passkey for it -
**Also plz increase its level from level 1 as i have to perform lots of task and generally people give it level 3 or atleast level 2.**
> Feedback backend frontend functionality working #278 done

- index.html
- src/components/Auth/LoginForm.jsx
- src/components/Auth/SignupForm.jsx
@param-code 
I have enhanced the scroll to top feature to make it align with the website styling
Kindly check it out
issue no: #270 
https://github.com/user-attachments/assets/23eb1917-e769-48f5-b06e-5a61300b1340
> enhanced scroll to top feature

- src/pages/Contributors.css
- src/pages/Contributors.jsx
Hello
I have added paging in the contributors page
> added paging to contributors

- src/pages/WorkTracker.jsx
Hello
I have fixed the UI issue on /worktracker page
> solved worktracker overlap issue

- src/components/Auth/Review.jsx
- src/components/SpotifyPlayer.css
[Bug]: rate us page is having issues #293 
Closes: #293 
fixes:
1. fixed the spoitify container which was interfering and was not handled by the implementor,
2. fixed the rateus page by making it responsive
3. gave new container design for spotify hover design.
>  [Bug]: rate us page is having issues #293 

- src/components/Auth/LoginForm.jsx
#309 issue 
LoginForm Component Enhancements
This update refines the LoginForm component for improved reliability and usability. Key changes include the following:
Password Toggle Optimization:
A togglePasswordVisibility function wrapped with useCallback to prevent unnecessary re-renders when toggling password visibility. This ensures smoother performance and state consistency.
UI Styling Adjustments:
Added styling for password input and eye icon to enhance visual clarity. Hover effects and borders were included for better user interaction.
Error Handling for Form Validation:
Integrated error messages for each field to improve user feedback when validation fails, using a structured error display in the LoginForm UI.
Console Debugging Tip:
Provided debugging instructions for developers to …
> Change the eye toggle button in Login Page

- src/components/Footer.jsx
I have changed the UI alignment of links from vertical to horizontal 
Issue #175
> changed footer ui to horizontal

- src/pages/Feedback.css
- src/pages/Feedback.jsx
- src/validations/validation.js
I have changed the UI of feedback form and also added validations to the fields
Issue #314
> Changed feedback ui

- src/components/Auth/LoginForm.jsx
- src/components/Auth/SignupForm.jsx
- src/pages/PrivacyPolicy.css
- src/pages/PrivacyPolicy.jsx
@param-code 
I have enhanced the privacy page, but i was not able to add the navbar to the signup page
Kindly check it out
issue no : #307 
from this 
https://github.com/user-attachments/assets/a50bae20-20d7-4518-a414-7a14ffef0132
to this
https://github.com/user-attachments/assets/36c42268-3757-47aa-9e0a-398afc2e1a8f
> enhanced privacy page

- package-lock.json
- package.json
- src/pages/PrivacyPolicy.css
- src/pages/PrivacyPolicy.jsx
This pull request introduces significant enhancements to the user interface of the Privacy Policy page to improve its visual appeal and user experience. 
****************************************
Issue No: #312 
****************************************
Before:
****************************************
After:
https://github.com/user-attachments/assets/5fc339d1-b924-471d-befe-bb037c83266a
****************************************
@param-code Please review and merge my code with appropriate lables.
> Enhanced the UI of  Privacy Policy page

- backend/controllers/subscribeController.js
- backend/index.js
- backend/models/User.js
- package-lock.json
- package.json
- src/components/Footer.jsx
This PR adds the subscribing implementaion to the backend and frontend of the website, successfully showing toast for the purpose.
> Add Subscribe 

- src/components/Footer.jsx
This pull request updates the footer section of the application to improve its layout and alignment. The "Stay Updated" section is now properly centered above the "Terms and Conditions" link, enhancing the overall user experience and visual appeal.
Issue No: #331 
***************
***************
These changes aim to create a more organized  footer that aligns with the overall design of the application.
**********
@param-code Please review and merge it.
> footer alignment

- backend/controllers/subscribeController.js
- backend/models/Newsletters.js
Newsletter email checking and storing the email for future reference.
closes #335 
what i have done -
1. adding a modal to store the emails unique.
2. checking the email exist or not with postman.
3. then again checking the emails with connecting frontend with it.
https://github.com/user-attachments/assets/55181e58-286e-4920-a8f2-225004e3baab
plz increase the level of this issue as it is of atleast level 2 or level 3 so plz do that.
> newsletter email checked : #335 done

- src/components/About.jsx
- src/pages/Contributors.css
Fix Issue - #334 
The website's color scheme is now consistent. I changed background colors and text colors all over the pages, which are now aligned with the overall theme. 
Hi @param-code, Can you please assign this issue under level 2 I made changes on other pages as well on both light and dark mode.
> Update Consistent Color Scheme Across All Pages

- backend/index.js
- backend/package-lock.json
- backend/package.json
- src/components/Footer.jsx
> Add Visitor Count Feature ✨ 

- backend/index.js
- backend/package-lock.json
- backend/passport.js
- backend/routes/googleauth.js
- src/components/Auth/SignupForm.jsx
This PR adds the backend implementation for signup with google and integrates it with the frontend.
> add google signup

- backend/package-lock.json
- src/components/About.jsx
overlap fix at about page between placeholder and button.
isssue_number: #348
> overlap fix between placeholder and button at about page

- backend/package-lock.json
- src/components/About.jsx
in about page at What Our Customers Say cards i am implement some animation and hover effect to enhanced all the cards styled.
issue_number: #349 
https://github.com/user-attachments/assets/6e80e736-f7fc-40ce-a01d-11790b1c1571
> UI enhanced of About  page What Our Customers Say cards
